### ISSUE TITLE
Show perk position

### ISSUE THREAD

**Issue by 3stadt** [3stadt/dbd_perk_slot_machine#30]
Optionally show on which page and row the chosen perks are located in dbd. This only works on a full set with all perks on 3. So it should be configurable via URL.

**Comment by jah0wl** [comment]
Perks are alphabetically ordered in DBD, so that's completely unnecessary.

**Comment by jah0wl** [comment]
But, In the other hand, it would be very helpful to have the result accesible by a permanent URL easy to share.

**Comment by 3stadt** [comment]
This issue was actually created before all tier 3 perks had the same color. ^^ I will close it, development on the project is currently dormant regarding new features. Reason here is a lack of contributors and me not having enough free time on my hands.
