### ISSUE TITLE
Design and implement a complete UI concept

### ISSUE THREAD

**Issue by leichteckig** [3stadt/dbd_perk_slot_machine#33]
**Is your feature request related to a problem? Please describe.**
At the moment, we reference the game UI to design the UI of our site. Works fine with limited functionality but sooner or later it won't, the increase of functionality without a concept could cause issues in maintainability and the UI to not stay consistent. 

**Describe the solution you'd like**
Design and implement an UI concept close to in-game design.

**Additional context**
Some ingame footage as reference:
![image](https://user-images.githubusercontent.com/29896429/54489516-5ee32f80-48ad-11e9-808d-f935a003cf30.png)
![image](https://user-images.githubusercontent.com/29896429/54489521-74585980-48ad-11e9-89b3-ef4b2c6b3f4f.png)

**Comment by 3stadt** [comment]
This issue is open for quite a while now and seems dormant. Please re-open if still relevant.
